//Problem 2: Even Fibonacci Numbers
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.

#include <stdio.h>

int fiboEvenSum(int n);

int main(){
    unsigned int n;
    printf("Input positive integer: \n");
    scanf("%d", &n);
    printf("Sum of all even numbers in fibonacci sequence that are lower then %d is equal to: %d", n, fiboEvenSum(n));
    return 0;
}

int fiboEvenSum(int n){
    int sum = 0;
    int counter = 0;
    int x,y,z;
    x=1;
    y=2;
    z=0;

    do{
        if (y % 2 == 0) sum+=y;
        z = x+y;
        x=y;
        y=z;
        counter++;
    }while(counter != n && y <= n);
    return sum;
}